Ecommerse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('App/',include('EcommerseApp.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

EcommerseApp/urls.py
from . import views
from django.urls import path, include

app_name = 'EcommerseApp'
urlpatterns = [

    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='proDetail')
]

cart/urls.py
from . import views
from django.urls import path

app_name="cart"
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'
urlpatterns=[
    path('search/',views.SearchResult, name='SearchResult'),
]

EcommerseApp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('EcommerseApp:products_by_category', args=(self.slug,))

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='category', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    def get_url(self):
        return reverse('EcommerseApp:proDetail', args=(self.category.slug,self.slug,))

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'product'

    def __str__(self):
        return '{}'.format(self.name)

cart/models.py
from django.db import models
from EcommerseApp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

searchapp/models.py
from django.db import models

# Create your models here.

EcommerseApp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage

# Create your views here.
def demo(request):
    return HttpResponse("Haiiii")


def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage, InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request, "category.html", {'category': c_page, 'products': products})


def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from EcommerseApp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

searchapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from EcommerseApp.models import Product
from django.db.models import Q


# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">

  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
  {% include 'header.html' %}
  {% include 'navbar.html' %}
  {% block content %}
  {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  this is the cart
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
{% if not cart_items %}
<head>
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is empty
        </h1>
        <br>
        <p class="text-center"></p>
        Please Click <a href="{% url 'EcommerseApp:allProdCart' %}">Here</a>to continue shopping.
</p>


    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping cart
        </h1>
        <br>
    </div>
    <div class="row mx-auto">
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
<thead class="my_custom_thead">
<tr>
<th colspan="5">
    Your Items
</th>
</tr>
</thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
            <td>
                <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
            </td>
            <td class="text-lef">
                {{cart_item.product.name}}
                <br>
                SKU:{{cart_item.product.id}}
                <br>
                Price: INR {{cart_item.product.price}}
                <br>
                Qty : {{cart_item.quantity}} x {{cart_item}}

            </td>
            <td>
                INR {{cart_item.sub_total}}
            </td>
            {% if cart_item.quantity < cart_item.product.stock %}
            <td>
                <a href="{% url 'cart:add_cart' cart_item.product.id %}">Add</a><br>
                    &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}">Remove</a><br>
                    &nbsp;&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}">Delete</a>
            </td>
            {% else %}
            <td>

                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}">Remove</a><br>
                    &nbsp;&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}">Delete</a>
            </td>

        </tr>
         {% endif %}

        </tbody>
        {% endfor %}
    </table>

</div>
   <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
       <table class="table my_custom_table">
           <thead class="my_custom_thead">
           <tr>
               <th>
                   Checkout
               </th>
           </tr>
           </thead>
           <tbody>
           <tr>
               <td>
                   Please review your shopping cart before proceeding with order payment.
               </td>
           </tr>
           <tr>
               <td class="text-left">
                   Your Cart Total is : <strong>{{ total }}</strong>

               </td>
           </tr>
           </tbody>

       </table>
       <div class="mx-auto">
           <a href="{% url 'EcommerseApp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue shopping</a>
<br>
           <br>


    </div>
        <div>

          <a href="/App/">
              <button class="btn btn-secondary btn-block" style="background-color:#87CEEB;">Payment</button>
            </a>

    </div>
    {% endif %}
   </div>
    </div>
</div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
       {{category.description|truncatewords:155}}
       {% else %}
            Welcome to ALLY STORE
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}}ALLY STORE
        {% else %}
            See our new Collections
    {% endif %}
    {% block content %}
        {% if category %}
            <div>
               <div class="row my_row_class">
                   <div class="mx-auto">
                   <p><a href="{% url 'EcommerseApp:allProdCat' %}" Our Product Collections></a> </p>
               </div>
                    </div>
            </div>
        {% endif %}
        <div class="mx-auto">
            {% if category %}
                <img src="{{category.image.url}}" alt="{{category.name}}" width="1520px" height="700px">
        </div>
        <br>
        <div>
            <h1 class="text-center my_title">{{category.name}}</h1>
            <p class="text-justify">{{category.description}}</p>
        </div>
            {% else %}
        <div>
            <img src="{% static 'img/banner.jpg' %}" alt="our product" width="1520px" height="420px">
        </div>
        <br>
        <div>
            <h1 class="text-center my_title">Our Product Collections</h1>
            <p class="text-justify" >Welcome to the world of variety!!!!</p>
        </div>
            {% endif %}
        <div class="container">
            <div class="row mx_auto">
                {% for product in products.object_list %}
                <div class="col-lg-4 mb-3 d-flex align-items-stretch">
                    <div class="card text-center" style="min-width:25rem;">
                        <a href="{{product.get_url}}"><img style="width:300px; height:300px;" class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                        <div class="card-body">
                            <h4>{{product.name}}</h4>
                            <p>{{product.price}}</p>
                        </div>
                    </div>

                </div>
                 {% endfor %}
            </div>
            <div class="mx-auto">
                {% if products.paginator.num_pages > 1 %}

                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}
                </div>
                {% endif %}
            </div>
            <br>
        </div>
    {% endblock %}
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">@Copywrite: Ally pvt ltd. All Rights Reseved</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{%url 'EcommerseApp:allProdCat' %}"></a>    </center>
</header>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

 <img src="{% static 'img/logo.png'%}" width="80" height="80">

        <li class="nav-item">
          <a class="nav-link" href="/App">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'EcommerseApp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'EcommerseApp:allProdCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
             {% endfor %}

          </ul>
        </li>
          {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}">Your cart({{item_count}})</a>
        </li>
          {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

       {{product.description|truncatewords:155}}

            Welcome to ALLY STORE

{% endblock %}


{% block title %}
    {% if category %}
        {{product.name}}ALLY STORE

            See our new Collections
    {% endif %}
{% endblock %}


{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'EcommerseApp:allProdCat' %}">Home</a>| <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    </div>
</div>

<div class="container">
    <br>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <div style="min-width:18rem;">
        <img src="{{product.image.url}}" alt="{{product.name}}">
    </div>
        </div>
        </div>
    <div>
        <div class="col-md-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
             <p class="text-justify my_rod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

templates/sample.html
<section class="bg-light pt-5 pb-5 shadow-sm">
  <div class="container">
    <div class="row pt-5">
      <div class="col-12">
        <h3 class="text-uppercase border-bottom mb-4">Equal height Bootstrap 5 cards example</h3>
      </div>
    </div>
    <div class="row">
      <!--ADD CLASSES HERE d-flex align-items-stretch-->
      <div class="col-lg-4 mb-3 d-flex align-items-stretch">
        <div class="card">
          <img src="https://i.postimg.cc/28PqLLQC/dotonburi-canal-osaka-japan-700.jpg" class="card-img-top" alt="Card Image">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">Dōtonbori Canal</h5>
            <p class="card-text mb-4">Is a manmade waterway dug in the early 1600's and now displays many landmark commercial locals and vivid neon signs.</p>
            <a href="#" class="btn btn-primary mt-auto align-self-start">Book now</a>
          </div>
        </div>
      </div>
      <!--ADD CLASSES HERE d-flex align-items-stretch-->
      <div class="col-lg-4 mb-3 d-flex align-items-stretch">
        <div class="card">
          <img src="https://i.postimg.cc/4xVY64PV/porto-timoni-double-beach-corfu-greece-700.jpg" class="card-img-top" alt="Card Image">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">Porto Timoni Double Beach</h5>
            <p class="card-text mb-4">Near Afionas village, on the west coast of Corfu island. The two beaches form two unique bays. The turquoise color of the sea contrasts to the high green hills surrounding it.</p>
            <a href="#" class="btn btn-primary mt-auto align-self-start">Book now</a>
          </div>
        </div>
      </div>
      <!--ADD CLASSES HERE d-flex align-items-stretch-->
      <div class="col-lg-4 mb-3 d-flex align-items-stretch">
        <div class="card">
          <img src="https://i.postimg.cc/TYyLPJWk/tritons-fountain-valletta-malta-700.jpg" class="card-img-top" alt="Card Image">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">Tritons Fountain</h5>
            <p class="card-text mb-4">Located just outside the City Gate of Valletta, Malta. It consists of three bronze Tritons holding up a large basin, balanced on a concentric base built out of concrete and clad in travertine slabs.</p>
            <a href="#" class="btn btn-primary mt-auto align-self-start">Book now</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   We have variety of products.
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for : <b>"{{query}}"</b></p>
</div>
 <div class="container">
            <div class="row mx_auto">
                {% for product in products %}
                <div class="my_bottom_margi col-9 col-sm-12 col-md-4 xol-lg-4">
                    <div class="card text-center" style="min-width:18rem;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                        <div class="card-body">
                            <h4>{{product.name}}</h4>
                            <p>{{product.price}}</p>
                        </div>
                    </div>

                </div>
                {% empty %}
                <div class="row mx-auto">
                    <p class="text-center my_search_text">0 results found</p>
                </div>
                {% endfor %}
            </div>
 </div>
{% endblock %}